import { jsPDF } from 'jspdf';

export const generatePDF = (title: string, resultData: any) => {
  const doc = new jsPDF();
  let yPos = 20;

  doc.setFontSize(22);
  doc.text(title || 'Exam Paper', 20, yPos);
  yPos += 15;

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('Generated by KaashAI', 20, yPos);
  yPos += 10;
  
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  yPos += 10;

  if (resultData && resultData.sections) {
    resultData.sections.forEach((section: any, idx: number) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text(`${idx + 1}. ${section.section_title}`, 20, yPos);
      yPos += 10;

      section.questions.forEach((q: any, qIdx: number) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(12);
        doc.setTextColor(40);
        const questionText = doc.splitTextToSize(`Q${qIdx + 1}: ${q.question}`, 170);
        doc.text(questionText, 20, yPos);
        yPos += questionText.length * 7 + 3;

        if (q.options) {
          q.options.forEach((opt: string, oIdx: number) => {
            const letter = String.fromCharCode(65 + oIdx);
            doc.text(`${letter}) ${opt}`, 30, yPos);
            yPos += 7;
          });
          yPos += 3;
        }

        if (q.answer) {
          doc.setFontSize(10);
          doc.setTextColor(0, 150, 0); // Green
          const answerText = doc.splitTextToSize(`Answer: ${q.answer}`, 160);
          doc.text(answerText, 30, yPos);
          yPos += answerText.length * 6 + 2;
          
          if (q.explanation) {
            doc.setTextColor(150, 150, 150);
            const explanationText = doc.splitTextToSize(`Explanation: ${q.explanation}`, 160);
            doc.text(explanationText, 30, yPos);
            yPos += explanationText.length * 6 + 5;
          }
        } else {
          yPos += 10; // Extra spacing for short answers
        }
      });
      yPos += 5;
    });
  }

  doc.save(`${title.replace(/ /g, '_')}_Exam.pdf`);
};
