import { jsPDF } from 'jspdf';

interface Question {
  question: string;
  options?: string[];
  answer?: string;
  explanation?: string;
  difficulty?: string;
  marks?: number;
}

interface Section {
  section_title: string;
  instruction?: string;
  questions: Question[];
}

interface ExamResult {
  title?: string;
  totalMarks?: number;
  duration?: string;
  sections?: Section[];
}

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const MARGIN_TOP = 20;
const MARGIN_BOTTOM = 25;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

function addPageNumber(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
    doc.text('Generated by KaashAI', PAGE_WIDTH - MARGIN_RIGHT, PAGE_HEIGHT - 10, { align: 'right' });
  }
}

function ensureSpace(doc: jsPDF, yPos: number, needed: number): number {
  if (yPos + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
    doc.addPage();
    return MARGIN_TOP;
  }
  return yPos;
}

export const generatePDF = (title: string, resultData: ExamResult) => {
  const doc = new jsPDF();
  let yPos = MARGIN_TOP;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20);
  const titleLines = doc.splitTextToSize(title || 'Examination Paper', CONTENT_WIDTH);
  doc.text(titleLines, PAGE_WIDTH / 2, yPos, { align: 'center' });
  yPos += titleLines.length * 8 + 4;

  // Duration & Marks
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  const metaParts: string[] = [];
  if (resultData?.duration) metaParts.push(`Duration: ${resultData.duration}`);
  if (resultData?.totalMarks) metaParts.push(`Max Marks: ${resultData.totalMarks}`);
  if (metaParts.length > 0) {
    doc.text(metaParts.join('    |    '), PAGE_WIDTH / 2, yPos, { align: 'center' });
    yPos += 8;
  }

  // Divider
  doc.setDrawColor(200);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, yPos, PAGE_WIDTH - MARGIN_RIGHT, yPos);
  yPos += 6;

  // Student Info
  yPos = ensureSpace(doc, yPos, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60);

  const fieldWidth = (CONTENT_WIDTH - 10) / 3;
  const fields = ['Name:', 'Roll No:', 'Section:'];
  fields.forEach((field, i) => {
    const x = MARGIN_LEFT + i * (fieldWidth + 5);
    doc.text(field, x, yPos);
    doc.setDrawColor(180);
    doc.line(x + doc.getTextWidth(field) + 2, yPos, x + fieldWidth, yPos);
  });
  yPos += 10;

  // General Instructions
  yPos = ensureSpace(doc, yPos, 20);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100);
  doc.text('GENERAL INSTRUCTIONS', MARGIN_LEFT, yPos);
  yPos += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const instructions = [
    'All questions are compulsory unless stated otherwise.',
    'Write your answers clearly and legibly.',
    'Marks for each question are indicated alongside.',
  ];
  instructions.forEach(instr => {
    doc.text(`• ${instr}`, MARGIN_LEFT + 2, yPos);
    yPos += 4;
  });
  yPos += 4;

  doc.setDrawColor(220);
  doc.line(MARGIN_LEFT, yPos, PAGE_WIDTH - MARGIN_RIGHT, yPos);
  yPos += 8;

  // Sections
  if (resultData && resultData.sections) {
    resultData.sections.forEach((section, sIdx) => {
      yPos = ensureSpace(doc, yPos, 20);

      // Section title
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30);
      doc.text(section.section_title || `Section ${String.fromCharCode(65 + sIdx)}`, MARGIN_LEFT, yPos);
      yPos += 6;

      // Section instruction
      if (section.instruction) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(120);
        const instrLines = doc.splitTextToSize(section.instruction, CONTENT_WIDTH - 5);
        doc.text(instrLines, MARGIN_LEFT + 2, yPos);
        yPos += instrLines.length * 4 + 4;
      }

      // Questions
      section.questions.forEach((q, qIdx) => {
        yPos = ensureSpace(doc, yPos, 25);

        // Question text with marks
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30);
        const marksLabel = q.marks ? ` [${q.marks} ${q.marks === 1 ? 'mark' : 'marks'}]` : '';
        const qText = `Q${qIdx + 1}. ${q.question}${marksLabel}`;
        const questionLines = doc.splitTextToSize(qText, CONTENT_WIDTH - 10);
        doc.text(questionLines, MARGIN_LEFT + 5, yPos);
        yPos += questionLines.length * 5.5 + 2;

        // Options
        if (q.options && q.options.length > 0) {
          doc.setFontSize(10);
          doc.setTextColor(60);
          q.options.forEach((opt, oIdx) => {
            yPos = ensureSpace(doc, yPos, 7);
            const letter = String.fromCharCode(65 + oIdx);
            const optLines = doc.splitTextToSize(`${letter}) ${opt}`, CONTENT_WIDTH - 20);
            doc.text(optLines, MARGIN_LEFT + 12, yPos);
            yPos += optLines.length * 5 + 1;
          });
          yPos += 2;
        } else {
          yPos += 8;
        }

        yPos += 3;
      });

      yPos += 6;
    });
  }

  addPageNumber(doc);

  const filename = `${(title || 'Exam').replace(/[^a-zA-Z0-9]/g, '_')}_Paper.pdf`;
  doc.save(filename);
};
